sudo: required
dist: trusty

jobs:
 include:
    - stage: backend
      name: "backend tests"
      language: java
      jdk: oraclejdk8    
      before_script:
        - cd Backend/szakdolgozat/
        - chmod +x mvnw
      script:
        - ./mvnw test
        
    - stage: backend
      name: "backend test and build"
      language: java
      jdk: oraclejdk8
      before_script:
        - cd Backend/szakdolgozat/
        - chmod +x mvnw
      script:
        - ./mvnw install

    # - stage: frontend
    #   name: "frontend build"
    #   language: node_js
    #   node_js:
    #     - 10.15.3
    #   before_script:
    #     - cd frondend/spark
    #     - npm install -g @angular/cli
    #     - npm install --save-dev @angular-devkit/build-angular
    #   script:
    #     - ng build

 notifications:
  email: false
