INSERT INTO `PERMISSION_DETAIL` (`ID`, `NAME`, `ROLE_TAG`) VALUES (1, 'Feladat kiosztása', 'ROLE_ADD_TASK');
INSERT INTO `PERMISSION_DETAIL` (`ID`, `NAME`, `ROLE_TAG`) VALUES (2, 'Szabadságok kiosztása', 'ROLE_HOLIDAY_ADMIN');
INSERT INTO `PERMISSION_DETAIL` (`ID`, `NAME`, `ROLE_TAG`) VALUES (3, 'Felhasználók kezelése', 'ROLE_USER_ADMIN');
INSERT INTO `PERMISSION_DETAIL` (`ID`, `NAME`, `ROLE_TAG`) VALUES (4, 'Projektek kezelése', 'ROLE_PROJECT_ADMIN');
INSERT INTO `PERMISSION_DETAIL` (`ID`, `NAME`, `ROLE_TAG`) VALUES (5, 'Feladatok kezelése', 'ROLE_ACTIVITY_GROUP_ADMIN');
INSERT INTO `PERMISSION_DETAIL` (`ID`, `NAME`, `ROLE_TAG`) VALUES (6, 'Jogosultságok kezelése', 'ROLE_PERMISSION_ADMIN');
INSERT INTO `PERMISSION_DETAIL` (`ID`, `NAME`, `ROLE_TAG`) VALUES (7, 'Listázás', 'ROLE_LISTING');
INSERT INTO `PERMISSION_DETAIL` (`ID`, `NAME`, `ROLE_TAG`) VALUES (8, 'Időbeosztás tervezése', 'ROLE_ACTIVITY_PLAN_ADMIN');

INSERT INTO `PERMISSION` (`ID`, `NAME`) VALUES (1, 'Adminisztráció');

INSERT INTO `USER` (`ID`, `CAN_LOG_IN`, `EMAIL`, `FIRST_NAME`, `LAST_LOGIN`, `LAST_NAME`, `LOGIN_NAME`, `MAX_HOLIDAY`, `PASSWORD`, `PERMISSION_ID`, `DELETED`) VALUES (1, TRUE, 'k.roli9955@gmail.com', 'Roland', '2019-10-31T12:32:20', 'Kotroczó', 'admin', 20, '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW', 1, false);

INSERT INTO `PERMISSION_DETAILS` (`PERMISSIONS_ID`, `DETAILS_ID`) VALUES (1, 1);
INSERT INTO `PERMISSION_DETAILS` (`PERMISSIONS_ID`, `DETAILS_ID`) VALUES (1, 2);
INSERT INTO `PERMISSION_DETAILS` (`PERMISSIONS_ID`, `DETAILS_ID`) VALUES (1, 3);
INSERT INTO `PERMISSION_DETAILS` (`PERMISSIONS_ID`, `DETAILS_ID`) VALUES (1, 4);
INSERT INTO `PERMISSION_DETAILS` (`PERMISSIONS_ID`, `DETAILS_ID`) VALUES (1, 5);
INSERT INTO `PERMISSION_DETAILS` (`PERMISSIONS_ID`, `DETAILS_ID`) VALUES (1, 6);
INSERT INTO `PERMISSION_DETAILS` (`PERMISSIONS_ID`, `DETAILS_ID`) VALUES (1, 7);
INSERT INTO `PERMISSION_DETAILS` (`PERMISSIONS_ID`, `DETAILS_ID`) VALUES (1, 8);

INSERT INTO `ACTIVITY_GROUP` (`ID`, `CAN_ADD_CHILD`, `NAME`, `PARENT_ID`, `DELETED`, `EASY_LOG_IN`) VALUES (1, TRUE, 'Tervezés', NULL, FALSE, FALSE );
INSERT INTO `ACTIVITY_GROUP` (`ID`, `CAN_ADD_CHILD`, `NAME`, `PARENT_ID`, `DELETED`, `EASY_LOG_IN`) VALUES (2, TRUE, 'Adatbázis tervezés', 1, FALSE, FALSE);
INSERT INTO `ACTIVITY_GROUP` (`ID`, `CAN_ADD_CHILD`, `NAME`, `PARENT_ID`, `DELETED`, `EASY_LOG_IN`) VALUES (3, FALSE, 'UML Diagram készítés', 1, FALSE, FALSE);
INSERT INTO `ACTIVITY_GROUP` (`ID`, `CAN_ADD_CHILD`, `NAME`, `PARENT_ID`, `DELETED`, `EASY_LOG_IN`) VALUES (4, TRUE, 'Fejlesztés', NULL, FALSE, FALSE);
INSERT INTO `ACTIVITY_GROUP` (`ID`, `CAN_ADD_CHILD`, `NAME`, `PARENT_ID`, `DELETED`, `EASY_LOG_IN`) VALUES (5, FALSE, 'Frontend implementálás', 4, FALSE, FALSE);
INSERT INTO `ACTIVITY_GROUP` (`ID`, `CAN_ADD_CHILD`, `NAME`, `PARENT_ID`, `DELETED`, `EASY_LOG_IN`) VALUES (6, FALSE, 'Backend implementálás', 4, FALSE, FALSE);
INSERT INTO `ACTIVITY_GROUP` (`ID`, `CAN_ADD_CHILD`, `NAME`, `PARENT_ID`, `DELETED`, `EASY_LOG_IN`) VALUES (7, FALSE, 'Munka kezdése', NULL, FALSE, TRUE);